workflow:
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH == 'develop'

# name of the Docker image, the Docker executor uses to run CI/CD jobs
image: openjdk:17-alpine

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
  - "Build"
  - "Test"

build-job:
  stage: Build
  script:
    - echo "Compiling the code..."
    - gradle bootJar
  artifacts:
    paths:
      - "build/libs/*.jar"
    when: on_success

test-job:
 stage: Test
 script:
   - echo "Testing the code..."
   #- ./gradlew check
   

