workflow:
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH == 'develop'

# name of the Docker image, the Docker executor uses to run CI/CD jobs
image: openjdk:17-alpine

# Stages, which define when to run the jobs. For example, stages that run tests after stages that compile the code.
stages:
	- build
	- test

build-job:
	stage: build
	script:
		- echo "Compiling the code..."
		- ./gradlew assemble
	artifacts:
	paths:
	- build/libs/*.jar

test-job:
	stage: test
	script:
		- echo "Testing the code..."
		- ./gradlew check